### PR TITLE
Bring the CI workflow in line with the fluent-kit setup

### PR DESCRIPTION
**Pull request by gwynne**

### CODE REVIEW

**Comment by gwynne** [comment]
CI failures are due to https://github.com/OpenKitten/MongoKitten/pull/245; the workflow itself is functioning correctly.

**Comment by Joannis** [comment]
@gwynne looking at your PR, you're using the latest 3.x and 4.x builds for the CI. However, MongoDB has a HUGE gap between individual 4.x and 3.x "minors". Some "minor" versions deprecate huge chunks of API, including authentication mechanisms. 

MongoDB 3.4 was supported until only a couple of months ago, and is a huge amount of features behind on 3.6. 3.6 doesn't differ as much from 4.2, but it's still a very notable gap.

See [their docs on support](https://www.mongodb.com/support-policy). This makes me wonder if a larger variety of MongoDB versions should be tested.

**Comment by gwynne** [comment]
> See [their docs on support](https://www.mongodb.com/support-policy). This makes me wonder if a larger variety of MongoDB versions should be tested.

@Joannis Basically the list of versions I can test is limited only by 1) the list of versions available as Docker images, and 2) the list of versions the underlying MongoKitten implementation supports

For reference, Docker Hub currently claims to have a number of variants all boiling down to versions 3.6, 4.0, 4.2, and 4.4 (ref: https://hub.docker.com/_/mongo/)

**Comment by Joannis** [comment]
That makes sense! 3.6 is what the 99.9% should be using. In practice however, a lot of people still have older 3.4 installations as well. I'd highly recommend any of those people to upgrade ASAP, but reality isn't like that.

**Comment by gwynne** [comment]
It looks like the `3.4` tag is actually still there as well, they're just not advertising it in the front-page README anymore (hardly a surprise for something lagging as badly as you describe).

**Comment by Joannis** [comment]
@gwynne Can you update the PR so the tests succeed? Excluding the swift nightly builds, because the unstable builds are unstable atm. I'd love to merge this soon, because of #31 

**EDIT:** I don't think this should be a blocker for #31 , but would love to rely on it for future PRs :)

**Comment by Joannis** [comment]
@gwynne do you want to update this PR?

**Pull request closed without merging**
